/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latihanteskoneksi;
import java.sql.*;

public class App {

    public static void main( final String[] args ) throws SQLException {
        //create connection for a server installed in localhost, with a user "root" with no password
        try (Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost/tokofilm", "root", null)) {
            // create a Statement
            try (Statement stmt = conn.createStatement()) {
                //execute query
                String query = "SELECT film.nama_film, member.nama_member, film.id_film FROM film JOIN detil_transaksi_film ON film.id_film=detil_transaksi_film.id_film JOIN transaksi_film ON transaksi_film.id_transaksi=detil_transaksi_film.id_transaksi JOIN member ON member.id_member=transaksi_film.id_member WHERE member.id_member=1";
                try (ResultSet rs = stmt.executeQuery(query)) {
                    //position result to first $query
                    rs.first();
                    System.out.println(rs.getString(2) + " Rents:");
                    do {
                        System.out.println(rs.getString(3)+". " + rs.getString(1)); //result is "Hello World!"    
                    } while (rs.next());
                }
            }
        }
    }
}
